version: "3.4"
services:
  tests:
    build:
      context: "."
      dockerfile: Dockerfile-tests
      target: tests
    links: 
      - rediproxy
    command: --redis-url=redisdb:6379 --proxy-url=rediproxy:8080
  rediproxy: 
    build: 
      context: "."
      dockerfile: Dockerfile
      target: release
    links: 
      - redisdb
    ports: 
      - "8080:8080"
    command: --redis-url=redisdb:6379
  redisdb: 
    image: redis
    ports: 
    - "6379:6379"
